version: '{build}'
image: Visual Studio 2017
configuration: Release
environment:
  matrix:
  - ARCH: Win32
  - ARCH: x64
install:
- cmd: >-
    mkdir build

    cd build

    cmake -A %ARCH% ..
build:
  project: build/wfind.sln
  verbosity: minimal
artifacts:
- path: build\Release\wfind.exe
  name: wfind
deploy: off
