version: '{build}'
pull_requests:
  do_not_increment_build_number: true
skip_tags: true
image: Visual Studio 2017
configuration: Release
environment:
  matrix:
  - ARCH: Win32
  - ARCH: x64
install:
- cmd: >-
    mkdir build

    cd build

    cmake -G "Visual Studio 15 2017" -A %ARCH% ..
build:
  project: build/wfind.sln
  verbosity: minimal
artifacts:
- path: build\Release\wfind.exe
  name: wfind
deploy: off
